### PR TITLE
engine_setup: Don't update ansible package

### PR DESCRIPTION
**Pull request by arachmani**
Don't update ansible package as we have version lock
on this package

Bug-Url: https://bugzilla.redhat.com/1887142
Signed-off-by: Asaf Rachmani <arachman@redhat.com>

### CODE REVIEW

**Comment by arachmani** [comment]
@sandrobonazzola, @mwperina, @mnecas can you please review?

**Review by sandrobonazzola — APPROVED** [review]
/lgtm

**Review by mwperina — APPROVED** [review]
+1

**Review by mnecas — APPROVED** [review]
LGTM

**Pull request merged**
