### PR TITLE
Remove "Update storage parameters" play

### PR DESCRIPTION
**Pull request by roniezr**
This patch is a WA for the following issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2079896

Jira ticket: RHV-45862

### CODE REVIEW

**Comment by roniezr** [comment]
@mwperina FYI, WDYT?

**Comment by nirs** [comment]
I guess that "WA" is "workaround". Lets keep the text free from
such shortcuts to make it more clear to everyone.

**Comment by ahadas** [comment]
@roniezr thanks for posting that. that's what we had in mind but first we need to analyze from the storage point of view why it was added and what's the implication for dropping it

**Comment by mnecas** [comment]
Resolved by https://github.com/oVirt/ovirt-ansible-collection/pull/500

**Pull request closed without merging**
