### PR TITLE
role: hosted_engine_setup: Add he_force_ip4 & he_force_ip6 to README

### PR DESCRIPTION
**Pull request by arachmani**
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/257

Signed-off-by: Asaf Rachmani <arachman@redhat.com>

### CODE REVIEW

**Review by kobihk — APPROVED** [review]

**Comment by mwperina** [comment]
Martin, shouldn't we have a changelog fragment for such change? I mean adding a new parameters to the role.
If so, then we really need some CI check ...

@mnecas

**Comment by arachmani** [comment]
@mwperina I didn't add new parameters to the role, just updated the README.

**Comment by mnecas** [comment]
I usually add all changelogs before the build but I will add the check to CI so every PR will have the changelog.
It would be nice to have it here because it is summed up for the build.

**Comment by mwperina** [comment]
> @mwperina I didn't add new parameters to the role, just updated the README.

Right, my bad, sorry

**Pull request merged**
