### PR TITLE
roles: hosted_engine_setup: Use command instead of firewalld module

### PR DESCRIPTION
**Pull request by arachmani**
Bug-Url: https://bugzilla.redhat.com/2092229
Signed-off-by: Asaf Rachmani <arachman@redhat.com>

### CODE REVIEW

**Comment by michalskrivanek** [comment]
OST failed with
11:11:55 E [ INFO ] TASK [ovirt.ovirt.hosted_engine_setup : Force updating the OVF store]

11:11:55 E [ ERROR ] ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "[Cannot ${action} Storage. Storage Domain OVF data is currently being updated.]". HTTP response code is 409.

11:11:55 E [ ERROR ] fatal: [localhost]: FAILED! =&gt; {"changed": false, "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot ${action} Storage. Storage Domain OVF data is currently being updated.]\". HTTP response code is 409."}



due to recent change that was imho unneeded..."If it ain't broke, don't fix it" ;)

**Comment by michalskrivanek** [comment]
..so now you have to fix it. @arachmani @didib I would perhaps suggest to revert and open similar PR again and wait for someone to implement it in a more robust way with the desired  cleanup. wdyt?

**Review by michalskrivanek — APPROVED** [review]

**Comment by arachmani** [comment]
> -1 Please describe the gluster issue before moving from firewalld module to command, maybe just gluster invocation needs to be changed ...

AFACT we have encountered this because there is no firewall module for python38 while ansible-controller uses python38.
I tried to figure out how come it works for RHV QE and not for RHHI-V QE but unfortunately didn't get to a conclusion.
RHHI-V QE fails to install HE role on both remote and local host while RHV QE is able to install on remote though doesn't run the role locally.
I tried executing the HE role directly on a local host and failed with the same error, note that `hosted-engine --deploy` works fine on a local host.
The solution for that is to use the `command` module or add `-e ansible_python_interpreter=/usr/bin/python3` when executing the role directly.

**Comment by arachmani** [comment]
> So one more question: I've just noticed https://bugzilla.redhat.com/show_bug.cgi?id=2041997 What optoin are we using for HE installation on locahost? Are we using the new `ansible_connection=local` or `ansible-playbook -c local` or are we using the old way from ansible <= 2.9

We use this yml file as an example when running the role directly:
https://github.com/oVirt/ovirt-ansible-collection/blob/bbee76a9a0ca313f461b58d4f0785f99c3e45254/roles/hosted_engine_setup/examples/hosted_engine_deploy_localhost.yml#L4

And a similar yml file when using `hosted-engine --deploy`:
https://github.com/oVirt/ovirt-hosted-engine-setup/blob/master/src/he_ansible/trigger_role.yml

I tried to use `firewalld` module on localhost along with `ansible-playbook -c local`, but got the same error.

**Review by mwperina — APPROVED** [review]
OK, so LGTM

**Review by mnecas — APPROVED** [review]
LGTM

**Pull request merged**
