### PR TITLE
Set hosted-engine VM with custom bios type (Q35+SeaBIOS)

### PR DESCRIPTION
**Pull request by ahadas**
To prevent its bios type from changing when the cluster's bios type changes

Bug-Url: https://bugzilla.redhat.com/1871694
Signed-off-by: Arik Hadas <ahadas@redhat.com>

### CODE REVIEW

**Comment by ahadas** [comment]
ci test

**Review by mnecas — APPROVED** [review]
LGTM

**Comment by arachmani** [comment]
@ahadas Please add Bug-Url in the commit message.

**Comment by ahadas** [comment]
@arachmani  done
also [passed OST](https://jenkins.ovirt.org/view/oVirt%20system%20tests/job/ovirt-system-tests_he-basic-suite-master/1763/)

**Comment by ahadas** [comment]
> also [passed OST](https://jenkins.ovirt.org/view/oVirt%20system%20tests/job/ovirt-system-tests_he-basic-suite-master/1763/)

actually, not sure the he-basic-suite-master job tests it with the specified ansible-collection..
@mnecas  is there a way to verify this PR using an automation job?

**Comment by arachmani** [comment]
In order to use ansible-collection in the he-basic-suite-master job, we need https://gerrit.ovirt.org/#/c/111385/ .

**Review by arachmani — APPROVED** [review]

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
