### PR TITLE
roles: hosted_engine_setup: replace virt_net and xml with commands

### PR DESCRIPTION
**Pull request by mnecas**
We need to replace all community modules because ansible-core 2.11 does not include any community modules.

New filter:
This patch adds `get_bridge_xml_to_dict` which converts stdout from `virsh net-dumpxml default` to the dictionary which has all bridge information. Later it is passed to the new template and used to configure the network bridge.

New template:
`network-config.j2` contains the jinja template from which the XML network configuration will be created.
Now users can specify both `he_ipv6_subnet_prefix` and `he_ipv4_subnet_prefix` and will support both modes before users could specify only one mode.

### CODE REVIEW

**Comment by michalskrivanek** [comment]
lgtm (if it works)

**Comment by almusil** [comment]
AFAICT looks good

**Comment by mnecas** [comment]
ci test please

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by mnecas** [comment]
ci test please

**Review by arachmani — CHANGES_REQUESTED** [review]
Tried to verify, on a none-clean host (host that runs a failed/successful deployment) after using `ovirt-hosted-engine-cleanup` the deployment failed with the following error:
```[ INFO  ] TASK [ovirt.ovirt.hosted_engine_setup : Create he-network-config.xml from network-config.j2 template]
[ INFO  ] changed: [localhost]
[ INFO  ] TASK [ovirt.ovirt.hosted_engine_setup : Update libvirt default network configuration, destroy]
[ ERROR ] fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["virsh", "net-destroy", "default"], "delta": "0:00:00.026791", "end": "2021-12-08 15:10:11.206631", "msg": "non-zero return code", "rc": 1, "start": "2021-12-08 15:10:11.179840", "stderr": "error: Failed to destroy network default\nerror: Requested operation is not valid: network 'default' is not active", "stderr_lines": ["error: Failed to destroy network default", "error: Requested operation is not valid: network 'default' is not active"], "stdout": "", "stdout_lines": []}
[ ERROR ] Failed to execute stage 'Closing up': Failed getting local_vm_dir
```

Networks list before the deployment:

``` 
# virsh -r net-list --all
 Name          State    Autostart   Persistent
------------------------------------------------
 ;vdsmdummy;   active   no          no
```

**Comment by mnecas** [comment]
Added the ignore_errors to the net-destroy think it should resolve the issue. 
@arachmani could you retry the env?

**Review by arachmani — APPROVED** [review]

**Pull request merged**
