### PR TITLE
HE install stops on missing file

### PR DESCRIPTION
**Pull request by xrow**
I had to add this change since the file wasn't there, but I don't know why it wasn't there in the first place. After the change HE worked for me.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by xrow** [comment]
ci test please

**Comment by xrow** [comment]
ci add to whitelist

**Comment by xrow** [comment]
ci test please

**Review by didib — COMMENTED** [review]
Thanks a lot for spending the time to investigate this and push this PR, but generally speaking, it should not be needed - the appliance already has this file. Can you perhaps look some more and try to understand why it was missing?

We had  a similar case some time ago [1], and as far as I could tell, it was due to some name resolution issue, causing the deploy process to connect to a wrong machine. Perhaps your case was similar? See comment 9 there [2] for my summary. Perhaps you can check your logs/infra and see if you can find something similar. If so, perhaps report this as new bug. Which version did you use? See also #277 - which was the fix for it - and #311 - which partially reverted the fix, but was needed for some other reason. I think yours is the first report since, so likely some corner case, but we still didn't manage to find the root cause... Thanks!

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1953029
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1953029#c9

**Review by sandrobonazzola — CHANGES_REQUESTED** [review]
@xrow can you please address @didib comment at https://github.com/oVirt/ovirt-ansible-collection/pull/401#pullrequestreview-835863974 ?

**Comment by xrow** [comment]
Hi,

if you think it is invalid that is fine. I try again anyway with the latetest version. Please close.

**Pull request closed without merging**
