### PR TITLE
hosted_engine_setup: hosted-engine.conf permissions

### PR DESCRIPTION
**Pull request by michalskrivanek**
- hosted_engine_setup: fix HE VM networking on recent CentOS Stream
- align hosted-engine.conf permissions to host-deploy

### CODE REVIEW

**Comment by michalskrivanek** [comment]
```
[root@ost-he-basic-suite-master-host-0 ~]# ls -l /etc/ovirt-hosted-engine/
total 12
-rw-r--r--. 1 root root  224 Aug  1 06:49 10-appliance.conf
-r--r-----. 1 vdsm kvm  1033 Aug  2 13:35 hosted-engine.conf
-rw-------. 1 root root  103 Aug  2 02:30 virsh_auth.conf
[root@ost-he-basic-suite-master-host-0 ~]# ls -l /var/run/ovirt-hosted-engine-ha
total 4
-rw-r-----. 1 vdsm kvm 1306 Aug  2 13:35 vm.conf
```

**Review by mwperina — APPROVED** [review]
+1

**Comment by arachmani** [comment]
Don't we need to change permissions also in this task:
https://github.com/oVirt/ovirt-ansible-collection/blob/509ad0c48a9489bdd811da9331174b694a411b75/roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml#L121

How does the first point in the first comment related to this PR -
`hosted_engine_setup: fix HE VM networking on recent CentOS Stream` ?

**Comment by mwperina** [comment]
> Don't we need to change permissions also in this task:
> 
> https://github.com/oVirt/ovirt-ansible-collection/blob/509ad0c48a9489bdd811da9331174b694a411b75/roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml#L121
> 
> How does the first point in the first comment related to this PR - `hosted_engine_setup: fix HE VM networking on recent CentOS Stream` ?

Asaf, could you please provide a patch for that?

**Comment by michalskrivanek** [comment]
> Don't we need to change permissions also in this task:
> 
> https://github.com/oVirt/ovirt-ansible-collection/blob/509ad0c48a9489bdd811da9331174b694a411b75/roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml#L121
> 
> How does the first point in the first comment related to this PR - `hosted_engine_setup: fix HE VM networking on recent CentOS Stream` ?

is the he_local_vm_dir not being cleared at the end? It has all sorts of temporary files and configurations used during installation, I don't think these permissions are going to solve all of them. We shouldn't leave this behind, and if we indeed don't then it's fine as is

**Comment by michalskrivanek** [comment]
> > Don't we need to change permissions also in this task:
> > https://github.com/oVirt/ovirt-ansible-collection/blob/509ad0c48a9489bdd811da9331174b694a411b75/roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml#L121
> > 
> > How does the first point in the first comment related to this PR - `hosted_engine_setup: fix HE VM networking on recent CentOS Stream` ?
> 
> is the he_local_vm_dir not being cleared at the end? It has all sorts of temporary files and configurations used during installation, I don't think these permissions are going to solve all of them. We shouldn't leave this behind, and if we indeed don't then it's fine as is

it seems to me it's cleaned in all cases - failures as well as full and partial execution.

**Review by arachmani — APPROVED** [review]
LGTM

**Pull request merged**
