### PR TITLE
roles: hosted_engine_setup: Remove SPICE from graphic protocols

### PR DESCRIPTION
**Pull request by arachmani**
Bug-Url: https://bugzilla.redhat.com/2026770
Signed-off-by: Asaf Rachmani <arachman@redhat.com>

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
+1

**Review by mwperina — APPROVED** [review]
+1

**Comment by mwperina** [comment]
Arik, could you please also take a look?

@ahadas

**Review by ahadas — APPROVED** [review]
I see QXL is not specified so removing SPICE and relying on libvirt & ovirt-engine to set a supported video device seems good to me

**Review by didib — APPROVED** [review]
As I wrote elsewhere (not sure where, sorry), from functionality POV I think we can completely get rid of the graphical console and keep only text/serial.

**Pull request merged**
