### PR TITLE
roles: hosted_engine_setup: Get admin user from engine-setup

### PR DESCRIPTION
**Pull request by didib**
So that it works also with keycloak

### CODE REVIEW

**Comment by didib** [comment]
This is an alternative to #475

**Review by mwperina — APPROVED** [review]
+1

**Comment by michalskrivanek** [comment]
lgtm

**Comment by didib** [comment]
Sorry, won't work. IIUC current ovirt-engine-keycloak setup plugin does not change ADMIN_USER.

**Review by mnecas — APPROVED** [review]
lgtm

**Pull request closed without merging**
