### PR TITLE
Add storage format

### PR DESCRIPTION
**Pull request by didib**
Allow passing storage_format as is allowed by the Python SDK.

Bug-Url: https://bugzilla.redhat.com/1932147

### CODE REVIEW

**Review by sandrobonazzola — APPROVED** [review]
LGTM but I would prefer some more people to review this one

**Review by arachmani — COMMENTED** [review]
The code LGTM, can you please add a changelog?

**Comment by didib** [comment]
Verified in [1] with [2] and current.

The commit messages in [2] are not very up to date - to get to this success, I also had to put host-0 to maintenance and remove it, prior to taking the backup.

Without current, something like [1] failed with the error message in the bug. With it, HE deploy succeeded. [1] failed later on adding host-1 (because it already exists).

So current PR can be merged as-is. If you prefer to not include the middle patch, I don't mind removing it, or you can remove it too if you want.

[1] https://redir.apps.ovirt.org/dj/job/ds-ost-baremetal_manual/32505

[2] https://github.com/oVirt/ovirt-system-tests/pull/93

**Comment by arachmani** [comment]
> So current PR can be merged as-is. If you prefer to not include the middle patch, I don't mind removing it, or you can remove it too if you want.

The middle commit contains code that looks similar to `create_storage_domain.yml`.
It's also not that trivial how to use it, I think we should remove it or perhaps combine them and add an explanation.

**Comment by didib** [comment]
> The middle commit contains code that looks similar to `create_storage_domain.yml`. It's also not that trivial how to use it, I think we should remove it or perhaps combine them and add an explanation.

I'd remove it.

**Comment by didib** [comment]
Ran OST, it passed HE deploy and failed later like before, as expected. So looks good to me, can be merged.

https://redir.apps.ovirt.org/dj/job/ds-ost-baremetal_manual/32907

**Review by arachmani — APPROVED** [review]
LGTM

**Pull request merged**
