### PR TITLE
roles: hosted_engine_setup: Set ownership of copied engine logs

### PR DESCRIPTION
**Pull request by didib**

### CODE REVIEW

**Review by almusil — APPROVED** [review]
Great, thanks

**Comment by arachmani** [comment]
@didib can you please add changelog?

**Comment by didib** [comment]
Just a rebase. Verified previous version on RHEL, where it's required for OST test_generate_openscap_report.

**Comment by didib** [comment]
I didn't create an issue for this. What should I write in the changelog? And where is the format documented?

**Review by arachmani — APPROVED** [review]

**Pull request merged**
