### PR TITLE
roles: hosted_engine_setup: Improve engine logs fetching

### PR DESCRIPTION
**Pull request by didib**
This is an addition to [1], missing there, updating also
partial_execution.yml . That said:

- This does not (usually?) reproduce on CI, perhaps simply because we
run there with low memory (thus forcing the kernel to sync often)

- I do not know well which parts of this code run on the host, which on
the engine, and what and when adds the engine to the inventory, so not
sure it would always work.

Copying the commit message from [1]:

Sometimes, on failed deploy attempts, engine-logs* directories are
created but left empty. I am guessing that this might be because the
files there are still cached in memory, and we do not fetch from the
engine vm itself (using e.g. ssh) but from the host, directly accessing
the vm disk image. So if, before that, we run 'sync' on the engine vm,
we have better chances to successfully get the logs from the image.

[1] https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/pull/325

Bug-Url: https://bugzilla.redhat.com/1844965

### CODE REVIEW

**Comment by mnecas** [comment]
@arachmani can you please review?

**Review by arachmani — APPROVED** [review]
Looks good to me

**Comment by didib** [comment]
> Looks good to me

Good enough so that I should remove from the commit message the second bullet :-) ?

I don't mind keeping it, though. Yesterday I spent quite some time trying to understand the current structure of this project, how it works, etc., including reading about the change from include_roles to import_roles, etc., and decided to give up for now, and just push this patch. Still working on verification.

**Comment by didib** [comment]
This is broken:

[ INFO  ] TASK [ovirt.ovirt.hosted_engine_setup : Sync on engine machine]
[ ERROR ] fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'engine'"}

I guess I'll have to learn a bit more...

**Review by sandrobonazzola — APPROVED** [review]
to my limited knowledge of anisble, looks good to me

**Review by arachmani — APPROVED** [review]

**Pull request merged**
