### PR TITLE
Ignore unreachable in full_execution "Sync on engine machine"

### PR DESCRIPTION
**Pull request by didib**
Bug-Url: https://bugzilla.redhat.com/1973640

### CODE REVIEW

**Comment by didib** [comment]
Verified by running with full_execution.

**Comment by arachmani** [comment]
@didib, I think `Sync on engine machine` task at this point will always fail (unless bootstrap VM and local VM hold the same IP address), so why not remove this task?

**Comment by didib** [comment]
> @didib, I think `Sync on engine machine` task at this point will always fail (unless bootstrap VM and local VM hold the same IP address), so why not remove this task?

I am not completely certain it will always fail. At the time, I simply added it right before every "Fetch logs from the engine VM" - in this case, the one done in final_clean.yml. Anyway, I don't mind removing, if you are certain it's never called.

**Comment by didib** [comment]
Anyway, I'd rather merge now and then think about removing. The bug is blocking QE, as they use full_execution.

**Comment by didib** [comment]
See #305 which is an alternative, preferred by Asaf. Personally I don't mind that much.

**Pull request closed without merging**
