### PR TITLE
hard code nic on_boot to True

### LINKED ISSUE #32: nic_on_boot boolean cannot be false
As per https://github.com/oVirt/ovirt-engine/blob/5b6a06433a5c352b53217e75b3219f84f4d41095/backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmInitToOpenStackMetadataAdapter.java#L48 it seems that  the cloud-init option to set nic_on_boot to false is not valid.

When I attempt to do so I see:

```"msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot add VM. Start On Boot selection in cloud-init configuration is invalid. Only 'true' is supported.]\". HTTP response code is 400."```

### PR DESCRIPTION
**Pull request by snecklifter**
False is not supported and results in an error so this should be
hard-coded to True.

Fixes #32

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by mnecas** [comment]
ci add to whitelist

**Comment by mwperina** [comment]
We can't just remove existing option, it would break backward compatibility. We need to deprecate it and keep it for at least some time

**Comment by mnecas** [comment]
> We can't just remove existing option, it would break backward compatibility. We need to deprecate it and keep it for at least some time

This is removing the only suboption, it will not fail/effect when switching from an older version of the modules. 

LGTM

**Comment by dominikholler** [comment]
What is the behavior of this PR if `nic_on_boot: false`?
Maybe we could have at a warning, that this option is ignored, if it is set to false?

**Comment by snecklifter** [comment]
@dominikholler because setting to `nic_on_boot: false` has never, AFAICT, worked. E.g. https://bugzilla.redhat.com/show_bug.cgi?id=1424786 so this is just removing the option (and therefore the confusion/complexity). A warning would only serve to mislead as its not supported by ovirt at all.

**Comment by snecklifter** [comment]
> We can't just remove existing option, it would break backward compatibility. We need to deprecate it and keep it for at least some time

Yes, this doesn't break anything, just removes the broken option from being exposed to the user.

**Comment by dominikholler** [comment]
What happens with your patch if `nic_on_boot: true` is set? Is this ignored?

**Comment by mnecas** [comment]
Yes, it will not fail because the parameter is the only suboption wich ansible does not enforce.

**Comment by dominikholler** [comment]
I see, thanks.
LGTM

**Pull request merged**
