### PR TITLE
Update operating system options

### PR DESCRIPTION
**Pull request by snecklifter**
Updates various modules with the current (4.4) list.

other_linux_kernel_4
other_linux_s390x
other_s390x
rhcos_x64
rhel_3x64
rhel_6_9_plus_ppc64
rhel_7_s390x
rhel_8x64
rhel_atomic7x64
sles_12_s390x
ubuntu_16_04_s390x
windows_2016x64
windows_2019x64

Removed (incorrect and duplicate):

windows_2008r2x64

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by mwperina** [comment]
Can't we fetch supported OS versions from API? If so, wouldn't it be better to introduce ovirt_vm_os_info module to fetch it for specific engine instance and just refer in documentation to this module?

@mnecas @andrej

**Comment by mwperina** [comment]
@akrejcir

**Comment by mnecas** [comment]
Okay I'll check if it would be better to create ovirt_vm_os_info. Meanwhile will keep the changes update if necessary.
Sorry about the revert my mistake.

**Comment by snecklifter** [comment]
> Okay I'll check if it would be better to create ovirt_vm_os_info. Meanwhile will keep the and changes update if necessary.
> Sorry about the revert my mistake.

No probs, I did wonder if there was an easier way of maintaining the list... :)

**Pull request merged**
