### PR TITLE
Disaster Recovery fixes after added to collections

### PR DESCRIPTION
**Pull request by barpavel**
The DR project was added to the "ovirt-ansible-collection" repository and merged in
#134
This PR fixes a few small issues with it.

Signed-off-by: Pavel Bar <pbar@redhat.com>

### CODE REVIEW

**Comment by barpavel** [comment]
Also for @shenitzky

**Comment by barpavel** [comment]
Verified today, October 28th.

**Review by shenitzky — APPROVED** [review]

**Comment by mnecas** [comment]
Please add the fragment.

**Comment by barpavel** [comment]
> Please add the fragment.

Done.

**Review by mnecas — APPROVED** [review]
LGTM

**Pull request merged**
