### PR TITLE
Drop usage of ipaddr filters and remove dependency on python-netaddr

### PR DESCRIPTION
**Pull request by michalskrivanek**

### CODE REVIEW

**Comment by michalskrivanek** [comment]
nto sure if it fixes #695 but it's a good thing in any case...

**Comment by michalskrivanek** [comment]
seems to work ok, it now broke on the next dependency, jmespath.

**Review by mnecas — APPROVED** [review]
Bit surprised that ip rule can accept IP/MASK instead of IP/CIDR. But looks good

**Comment by michalskrivanek** [comment]
tested on el9 with ipv4-only and dual stack

**Comment by michalskrivanek** [comment]
> Bit surprised that ip rule can accept IP/MASK instead of IP/CIDR. But looks good

ah, so that's what it does!:-D dunno, but if the sacred OST says green then why would I even check

**Comment by michalskrivanek** [comment]
That’s one small step for man, one giant leap for mankind!

**Comment by mnecas** [comment]
> > > Bit surprised that ip rule can accept IP/MASK instead of IP/CIDR. But looks good
> > 
> > 
> > ah, so that's what it does!:-D dunno, but if the sacred OST says green then why would I even check
> 
> reading documentation despite them trying to document the syntax using formal grammar it doesn't really seem to be defined what format it accepts. In other places ip's PREFIX states it's CIDR. Yet, it indeed works just fine, even on RHEL 8.6:
> 
> ```
> # ip rule add from 192.168.8.3/255.255.255.0 priority 101 table main
> # ip rule
> 101:    from 192.168.8.3/24 lookup main
> ```
> 
> eh....so let's proceed...:)

Yeah I did same test. Also could not find which format they require/support

**Pull request merged**
